remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
# Try adding or modifying one of these if it's not there:
show_downloads: false
show_github_ribbon: false
show_view_on_github: false
github: [metadata_repo: false] # Sometimes this can influence it too

title: '#KaponHindiTapon'
description: bawat buhay ay mahalaga 
#(Every life is precious.) 
#This site champions spay and neuter programs as a key solution, while raising awareness to stop the heartbreaking cycle of pet abandonment and animal cruelty. Find resources and take action.
