remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Kapon Hindi Tapon
description: Bawat buhay ay mahalaga. 
(Every life is precious.) 
#This site champions spay and neuter programs as a key solution, while raising awareness to stop the heartbreaking cycle of pet abandonment and animal cruelty. Find resources and take action.
